import Footer from "./components/footer";
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="flex flex-col h-screen w-screen justify-between">
                {children}
                <Footer />
            </body>
        </html>
    );
}
